### PR TITLE
Added Lab System Services

### PR DESCRIPTION
**Pull request by njpires20**
- Added Lab system services to default menu
- Created lab system service view with UI to accept lab type, lab, staff ID and Patient ID

### CODE REVIEW

**Review by NickFrangie — DISMISSED** [review]
Looks good 👍

**Review by bdvuong — DISMISSED** [review]
Looking good! 👍

**Comment by MacCode7110** [comment]
Looks good

**Review by MacCode7110 — DISMISSED** [review]
Looks good

**Review by mmueting — APPROVED** [review]

**Review by JohnMuirhead000 — APPROVED** [review]

**Review by MacCode7110 — APPROVED** [review]
Lab System requests work

**Pull request merged**
